name: Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Version
        shell: bash
        run: |
          sed -i -e 's/^version = "\(.*\)"/version = "${{ inputs.version }}"/g' Cargo.toml

      - name: Setup Zig
        uses: mlugg/setup-zig@v1

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
     
      - name: Setup zigbuild
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --locked cargo-zigbuild
          
      - name: Assemble
        uses: jreleaser/release-action@v2
        with:
          arguments: assemble
        env:
          JRELEASER_PROJECT_VERSION: ${{ inputs.version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PLATFORM_OVERRIDE: ${{ matrix.job.jreleaser_platform }}

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jreleaser-assemble-${{ matrix.job.target }}
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: artifact-${{ matrix.job.target }}
          path: |
            out/jreleaser/assemble/helloworld/archive/*.zip
